data_ingestion:
  train_test_split_ratio: 0.8

data_processing:
  numerical_columns:
    - number of adults
    - number of children
    - number of weekend nights
    - number of week nights
    - car parking space
    - lead time
    - repeated
    - P-C
    - P-not-C
    - average price
    - special requests

  categorical_columns:
    - type of meal
    - room type
    - market segment type
    - date of reservation
    - booking status
  
  skewness_threshold: 5
  no_of_features: 10